#!/bin/sh

exec java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED $JAVA_OPTIONS -cp /opt/otp/otp.jar:/opt/otp/jython-standalone-2.7.3.jar org.opentripplanner.standalone.OTPMain $@